name: 刷步数

on:
  schedule:
    - cron: '20 0,2,4,6,8,14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz
          python3 main.py |tee update.log
      - name: update info
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
          git commit -m "[${current}] update log"
          git push origin master
